# Автор Мазин Пётр aka Kill100, Он же Feyverk[Kill]Soft
# ------
# Полный список ID блоков смотрите в вики
# ------
# autorotation - true - плагин повернёт игрока при посадки на стул, false - как сел так и окжется D
# sneaking: Если стоит true, вы должны красться/присесть/зажать шифт и щелкнуть правой кнопкой, что бы сесть.
# distance: Максимальное расстояние между сиденьем (центральный блок) и игроком что бы можно было сесть (что бы предотвратить провалы сквозь стены итд).
# --------- bench ------------ описываются скамейки
# bench.blocks: Укажите блоки и расстояние на которое надо сесть. Для примера:
# Block-ID(:Block-sub-ID): высота посадки
# 53: 0.5
# 44:2: 0.3
# bench.austeritystructure: анализатор правильности скамейки
# bench.austeritystructure:hard - игрок может сидеть только на стульях состоящих из ступеньки/ступенек к которым прикреплены ступеньки с зади и по бокам скамейки (скамейка может состоять из нескольких ступенек разных пород идущих в ряд).
# bench.austeritystructure:medium - может сесть на ступеньки с зади которых прикреплены таблички,
# bench.austeritystructure:low - может сесть на ступеньки у которых таблички есть только по бокам, 
# bench.austeritystructure:disabled - игрок может сесть просто на ступеньку.
# bench.maxlenghtbench - максимальная длина скамейки из ступенек
# bench.enablebench - может ли игрок вобще сидеть на стульях? true/false
# ----------- sofa ----------  описываются диваны
# sofa.enablesofa - можно ли вобще сидеть на диванах? true/false
# sofa.maxlenghtsofa - максимальная длина дивана не менее 1.
# sofa.sittingsofablocks - список сидушек дивана и высоты посадки
# sofa.backsofablocks - список спинок дивана
# sofa.indentationononeblock - отступать на 1 блок. Если включен то на диван нельзя садится если перед сидушкой есть блок отличный от воздуха.
# ------------- WARNING!!!!!!!!! EXPEREMENTAL!!!!-----------
# antifallthrough true - проверяет провалились ли игроки под стул во время сиденья или нет. Если да поднимает
# Настоятельно рекомендуем не включать!!! Если такая проблема действительно есть то можно включить!!!!!!!!!!
# Если плагин будет выбивать ошибку или бедет конфликтовать с другим плагинами 
# (Особенно если они телепортируют игрока) то необходимо отключить данную опцию
antifallthrough: false
autorotation: true
sneaking: true
distance: 2
update:
# Check for updates
      updatechecked: true
# delay in minutes
      updatetimeout: 60
bench:
      enablebench: true
      maxlenghtbench: 12
      austeritystructure: low
      blocks:
        '53:0': 0.5
        '53:1': 0.5
        '53:2': 0.5
        '53:3': 0.5
        '67:0': 0.5
        '67:1': 0.5
        '67:2': 0.5
        '67:3': 0.5
        '108:0': 0.5
        '108:1': 0.5
        '108:2': 0.5
        '108:3': 0.5
        '109:0': 0.5
        '109:1': 0.5
        '109:2': 0.5
        '109:3': 0.5
        '114:0': 0.5
        '114:1': 0.5
        '114:2': 0.5
        '114:3': 0.5
        '128:0': 0.5
        '128:1': 0.5
        '128:2': 0.5
        '128:3': 0.5
        '134:0': 0.5
        '134:1': 0.5
        '134:2': 0.5
        '134:3': 0.5
        '135:0': 0.5
        '135:1': 0.5
        '135:2': 0.5
        '135:3': 0.5
        '136:0': 0.5
        '136:1': 0.5
        '136:2': 0.5
        '136:3': 0.5
        '156:0': 0.5
        '156:1': 0.5
        '156:2': 0.5
        '156:3': 0.5
sofa:
    enablesofa: true
    indentationononeblock: false
    maxlenghtsofa: 8
    sittingsofablocks:
        '44:0': 0.5
        '44:1': 0.5
        '44:2': 0.5
        '44:3': 0.5
        '44:4': 0.5
        '44:5': 0.5
        '44:6': 0.5
        '44:7': 0.5
        '126:0': 0.5
        '126:1': 0.5
        '126:2': 0.5
        '126:3': 0.5
    backsofablocks:
        - '35:0'
        - '35:1'
        - '35:2'
        - '35:2'
        - '35:4'
        - '35:5'
        - '35:6'
        - '35:7'
        - '35:8'
        - '35:9'
        - '35:10'
        - '35:11'
        - '35:12'
        - '35:13'
        - '35:14'
        - '35:15'